import Header from './Header'
import Home from './Home'
import Login from './Login'
import parentVendor from './parentVendor'
import Users from './Users'
import Vendors from './Vendors'
import Voucher from './Voucher'
import Merchant from './Merchant'
import Main from './Main'
import Staff from './Staff'
import Cashout from './Cashout'
export {Header , Home , Login , parentVendor , Users , Vendors , Voucher , Merchant , Main , Staff , Cashout }